sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=2.3.2
    - env: ANSIBLE_VERSION=2.4.2

before_install:
  - sudo apt-get -y install software-properties-common
  - sudo apt-get -y install python-pip
  - sudo pip install ansible==$ANSIBLE_VERSION
  - ansible --version

install:
  - sudo ansible-galaxy install moira-alert.moira-trigger-role
  - sudo mkdir /etc/fake_api/
  - sudo cp ./tests/fake_api.py /etc/fake_api/fake_api.py
  - sudo cp ./tests/fake_api.conf /etc/init/fake_api.conf

before_script:
  - sudo service fake_api start

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --connection=local --sudo -vvv ./tests/fake_api.yml

after_script:
  - sudo service fake_api stop
  - sudo cat /var/log/upstart/fake_api.log
